spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  rabbitmq:
    host: ${RABBIT_HOST}
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

logging:
  level:
    root: ERROR
    com.codeplatform.backend: INFO