spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/codeplatform_db
    username: postgres
    password: vishal
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.codeplatform.backend: DEBUG
    org.hibernate.SQL: DEBUG