spring:
  application:
    name: problemSubmit
  main:
    web-application-type: none
  rabbitmq:
    host: localhost
    port: 5672
    username: cp_user
    password: cp_pass

judge0:
  base-url: http://13.234.30.137:2358

logging:
  level:
    com.worker.problemSubmit : WARN